---
resource_types:
  - name: gcs-resource
    type: docker-image
    source:
      repository: danieljoneseb/gcs-resource-with-default


resources:
- name: git
  type: git
  source:
    uri: https://github.com/DanielJonesEB/gcp-pipeline.git
    branch: master
- name: tfstate
  type: gcs-resource
  source:
    bucket: {{project_id}}
    json_key: {{gcp_credentials_json}}
    versioned_file: ci/terraform.tfstate
    default_content: ""

jobs:
- name: setup-ci
  plan:
  - get: git
    trigger: true
  - get: tfstate
  - task: bootstrap-terraform
    file: git/tasks/bootstrap.yml
    input_mapping:
      gcp-bootstrap: git
    params:
      TF_VAR_gcp_creds: {{gcp_credentials_json}}
      TF_VAR_project_id: {{project_id}}
  - put: tfstate
    params:
      file: tfstate-out/terraform.tfstate

- name: teardown-ci
  plan:
  - get: git
  - get: tfstate
  - task: bootstrap-terraform
    file: git/tasks/teardown.yml
    input_mapping:
      gcp-bootstrap: git
    params:
      TF_VAR_gcp_creds: {{gcp_credentials_json}}
      TF_VAR_project_id: {{project_id}}
