---
resource_types:
  - name: gcs-resource
    type: docker-image
    source:
      repository: frodenas/gcs-resource


resources:
- name: git
  type: git
  source:
    uri: https://github.com/DanielJonesEB/gcp-pipeline.git
    branch: master
- name: tfstate
  type: gcs-resource
  source:
    bucket: {{project_id}}
    json_key: {{gcp_credentials_json}}
    versioned_file: ci/terraform.tfstate

jobs:
- name: setup-ci
  plan:
  - get: git
    trigger: true
  - task: bootstrap-terraform
    file: git/tasks/bootstrap.yml
    input_mapping:
      gcp-bootstrap: git
    params:
      TF_VAR_gcp_creds: {{gcp_credentials_json}}
      TF_VAR_project_id: {{project_id}}
  - put: tfstate
    params:
      file: tfstate/terraform.tfstate
