platform: linux

image_resource:
  type: docker-image
  source:
    repository: ljfranklin/terraform-resource
    tag: 0.11.13

inputs:
- name: gcp-bootstrap
- name: tfstate

run:
  path: gcp-bootstrap/tasks/teardown.sh

params:
  BILLING_ACCOUNT_ID: {{billing_account_id}}
  BUCKET_LOCATION: {{bucket_location}}
  FOLDER_NAME: {{folder_name}}
  GCP_CREDENTIALS_JSON: {{gcp_credentials_json}}
  ORGANIZATION_ID: {{organization_id}}
  PROJECT_ID: {{project_id}}
  PROJECT_NAME: {{project_name}}
